-- MySQL Script generated by MySQL Workbench
-- Mon 02 Oct 2017 07:14:09 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PaintbrushEducationRoot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PaintbrushEducationRoot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PaintbrushEducationRoot` DEFAULT CHARACTER SET utf8 ;
USE `PaintbrushEducationRoot` ;

-- -----------------------------------------------------
-- Table `PaintbrushEducationRoot`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PaintbrushEducationRoot`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `authenticationKey` VARCHAR(255) NULL,
  `localdbaddress` VARCHAR(255) NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
